### ISSUE TITLE
Missing git tags / wrong homepage on pypi

### ISSUE THREAD

**Issue by olivierdalang** [icpac-igad/wagtail-leaflet-widget#3]
Hi !

There's no tags in this git repository matching the pypi release, making it hard to know what exactly is on pypi.
Also, the homepage link on https://pypi.org/project/wagtailleafletwidget/ is broken.

It would be nice to fix this as it makes contributions easier

**Comment by erick-otenyo** [comment]
Fixed by release 1.0.2
